name: cryptoglide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  fl_chart: ^0.70.2
  web_socket_channel: ^3.0.2
  shimmer:
  provider: ^6.1.4
  google_fonts: ^6.2.1
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/icons/BTCUSDT.png
    - Assets/icons/ADAUSDT.png
    - Assets/icons/ETHUSDT.png
    - Assets/icons/SOLUSDT.png
    - Assets/icons/XRPUSDT.png
    - Assets/icons/DOGEUSDT.png
    - Assets/icons/BNBUSDT.png
    - Assets/icons/MATICUSDT.png
    - Assets/icons/DOTUSDT.png
    - Assets/icons/LTCUSDT.png
    - Assets/icons/FUNUSDT.png
